### ISSUE TITLE
Registration Target Audience Dropdown: selecting "Everyone" should deselect all others

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#108]
When registering an organization, there is an input for target audience; one of the choices is "everyone." If a user selects this option, it should automatically select all others or deselect all others. It doesn't make sense to select everyone and teens or to select everyone plus all the others.
![image](https://user-images.githubusercontent.com/40341857/86561839-63a27b80-bf16-11ea-86af-1ba932fcdf49.png)

**Comment by RafaelCenzano** [comment]
Or should it select all of them? So in filters, it will show up on all of them?

**Comment by rexliu3** [comment]
Ya. Selecting everyone should add all the tags/people to that organization. So in the filters, it has all the types

**Comment by jinhao27** [comment]
currently implementing. What is the desired goal for the final display? Should it display kids, teens, adults, seniors, and groups if the user selects everyone? Or should it just show everyone?
