### ISSUE TITLE
Registration Page: Add "Others" option for  Referrer

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#109]
When registering an organization, under the referrer dropdown selection, add an "others" option. This should create an input field below the drop down asking to enter the other referrer. This is particularly useful as the page may be advertised on new platforms but you haven't added that platform to the list yet. Also, if they enter an organization that is on the list (i.e. they couldn't find it), automatically select the organization they typed in.
![image](https://user-images.githubusercontent.com/40341857/86562446-8f723100-bf17-11ea-9912-0258a02fd56e.png)

**Comment by angc7** [comment]
Enhancement has been added; closing.
