### ISSUE TITLE
Registration Page: clicking the text of "I agree to the..." should check the box

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#110]
When registering an organization, clicking the "I agree to the Launch Tech LLC Terms of Service" text should check the box as is the case on many other websites. This is purely for convenience.
![image](https://user-images.githubusercontent.com/40341857/86562915-5ab2a980-bf18-11ea-9ca7-06f3215b6366.png)

**Comment by RafaelCenzano** [comment]
This should be a fix #113

**Comment by angc7** [comment]
Fixed and successfully tested; closing.
