### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by RafaelCenzano** [launchtechllc/npocore#112]
I'm not sure if this is just a problem with this logo but it wasn't accepted by npocore. But after opening it in gimp and re-exporting it npo core accepted it as a valid image.
The buggy image:
![Logo_buggy](https://user-images.githubusercontent.com/32753063/86671518-94cc8b80-bfaa-11ea-8e5c-84ebec97e689.png)
The fixed version:
![Logo_fixed](https://user-images.githubusercontent.com/32753063/86671540-9a29d600-bfaa-11ea-92ca-d81751c2cbf4.png)
Again the only difference is the fixed one was re-exported, and i'm not sure if this is an issue with the image or with npo core

**Comment by angc7** [comment]
Reproducible on macbook air, google chrome

**Comment by angc7** [comment]
The buggy image works for me, on Macbook Air  Catalina + Google Chrome
<img width="1121" alt="Screen Shot 2020-07-07 at 3 47 33 PM" src="https://user-images.githubusercontent.com/65053157/86834741-2e5a7280-c069-11ea-92cd-7b4cfb0b993c.png">
