### ISSUE TITLE
Can overwrite other organizations password if you have their email and spam the button enough

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#26]
To reproduce
1. Create an organization
2. Create a second organization but with the same name and email but different password
3. Login using the second password

**Comment by calixo888** [comment]
@MitchellArtz how were you able to create an organization with the same name and email?

**Comment by MitchellArtz** [comment]
Not quite sure, sometimes it shows internal error and other times it doesn't

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
