### ISSUE TITLE
Application and Internal Server Error When Registering

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#27]
When the following inputs were given to register a new organization, an application error occurred. When same input was retried, Internal Server Error.

Organization Name: Test
Organization Email: [A long string of letters and numbers]@gmail.com
Organization Description: [Long string of characters, symbols, and numbers]
Password: [Long string of characters, symbols, and numbers]
Organization Logo: [.3mf file]
Target Audience: [All Selected]
Cause: [All Selected]
Looking for: [All Selected]
[No Organization links + Agreed to Terms of Service]

**Error Shown:**
![image](https://user-images.githubusercontent.com/40341857/84964819-fa231000-b0c1-11ea-915b-289f1eae740d.png)
![image](https://user-images.githubusercontent.com/40341857/84965061-b67cd600-b0c2-11ea-91f8-4bc6038ba826.png)

**Possible Causes:**
- Overflow Error
- Logo was not of an image file type
- Server cannot handle large strings

**Comment by MitchellArtz** [comment]
Internal error caused by writing over a previous organizations name, my old test organization (tested this theory and correct)
Application error seems to be caused by a long string of text as that's how I reproduce it. (Tried uploading different file types and had no effect)

**Comment by MitchellArtz** [comment]
Tested on new version, fixed and closed
