### ISSUE TITLE
invalid emails during registration

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#30]
Allows users to input invalid emails (eg. 123@123) as long as it's in the format of "text@text". 

Suggestions:
- ensures that "@" is followed by "gmail.com", "hotmail.com" etc. before the user is allowed to press the register button
- display "please enter a valid email address" if the email is invalid

**Comment by RafaelCenzano** [comment]
Custom domains require things besides just gmail, hostmail, etc.

**Comment by calixo888** [comment]
@mollyxu I think I've gotten this brought up before. It's a matter of whoever is registering, if they're not going to put in a valid email than they can't really use NPO core the right way

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
