### ISSUE TITLE
Text at the bottom of the homepage "(c) 2020....rights reserved" is overlapping Register button (Mobile only)

### ISSUE THREAD

**Issue by anunaykumar03** [launchtechllc/npocore#31]
The copyright text overlaps the Register your NPO button and makes it difficult to click on the desired button. 

The bug only shows on mobile and not on Windows.

**Comment by MitchellArtz** [comment]
Bug only occurs for me when the menu is open

**Comment by calixo888** [comment]
@anunaykumar03 can you attach a screenshot for reference?

**Comment by anunaykumar03** [comment]
![77F1047F-2599-42DD-8530-97FF41B10F45](https://user-images.githubusercontent.com/66542316/85071517-7b36e180-b16c-11ea-9220-a5f6f3979937.png)

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
