### ISSUE TITLE
After uploading enourmous profile picture, the account is unusable 

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#34]
Also displays an internal server error
https://www.npocore.com/@test345

**Comment by jinhao27** [comment]
Can you elaborate on this? The link also doesn't seem to lead to anything, or it just times out

**Comment by MitchellArtz** [comment]
Whenever I upload a profile picture with an insane file size, an internal error pops up, the link wouldn't work now as the account is deleted, however, this issue doesn't seem to be resolved on the test environment.

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
