### ISSUE TITLE
bit.ly/mindsparksubmissions link on Featured Opportunity Posts is invalid

### ISSUE THREAD

**Issue by anunaykumar03** [launchtechllc/npocore#36]
Go to Opportunities tab and click on Submit now button for Mind Spark opportunity. 

New tab opens with the Bit.ly url but displays 404 error (page not found).

![Mind Spark submissions error](https://user-images.githubusercontent.com/66542316/84966534-a1a24180-b0c6-11ea-9f4a-f51850a2fcad.PNG)

**Comment by MitchellArtz** [comment]
I believe this is more of an issue of the end user not putting out the correct link, nothing developers can do about it.

**Comment by MitchellArtz** [comment]
Not an issue we can fix, closing for that reason
