### ISSUE TITLE
Overwrite post pictures

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#41]
1. Get the name of a picture from a post or profile picture
2. Upload an image with a larger file size than the previous image with the same name

You have successfully overwritten a post image

**Comment by MitchellArtz** [comment]
![image](https://user-images.githubusercontent.com/32065190/84968122-c35df180-b0e3-11ea-90a9-e46a412885f7.png)

**Comment by RafaelCenzano** [comment]
Rename the file to the organization id or control the name so people can't overwrite other pictures? Except for the problem that you can have duplicate organization ids. Possibly want a unique number id or limit organizations with the same name?

**Comment by calixo888** [comment]
Made each upload generate new UUID
