### ISSUE TITLE
Organizations-Filter by name not working

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#42]
Filter by name doesn't work when the first letter is typed.

eg. When "m" is typed into the filter bar, "simply neuroscience" appears higher up in the search query than "modern divergence" 
![Screen Shot 2020-06-17 at 6 30 55 PM](https://user-images.githubusercontent.com/64995721/84967387-aff15d00-b0c8-11ea-8b39-c8206298d7de.png)

eg. When "s" is typed into the filter bar, "plannr consulting" appears higher up in the search query than "simply neuroscience" 
![Screen Shot 2020-06-17 at 6 33 15 PM](https://user-images.githubusercontent.com/64995721/84967532-0363ab00-b0c9-11ea-8bbd-2cb4fc3f88b7.png)

**Comment by calixo888** [comment]
Duplicate of #18
