### ISSUE TITLE
Cannot edit or remove posts; cannot delete acccount

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#43]
After writing a test code with a very long string of characters, numbers, and symbols, the post could not be deleted or removed. In addition, the account could not be deleted. 

Suggestion:
- Allow posts to be editable and deletable
- Allow organization accounts to be editable and deletable

**Comment by calixo888** [comment]
@rexliu3 Right now posts are deletable not editable, and organizations are editable but not deletable

**Comment by calixo888** [comment]
New features:
* Add edit mode for posts

**Comment by calixo888** [comment]
Fixed - added edit mode
