### ISSUE TITLE
Registration - Dropdown menu - select all feature

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#46]
Like the "everyone" option in the "select audience" dropdown menu, it would be nice if there's a "select all" option for following dropdown menu during registration as well.
![Screen Shot 2020-06-17 at 6 45 18 PM](https://user-images.githubusercontent.com/64995721/84968159-b385e380-b0ca-11ea-8acb-b0d24ce7e283.png)

**Comment by calixo888** [comment]
Great suggestion @mollyxu! That may be something to implement later on

**Comment by jinhao27** [comment]
done
