### ISSUE TITLE
Can delete other user's posts

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#47]
![image](https://user-images.githubusercontent.com/32065190/84968728-3025bb80-b0e5-11ea-8bc0-e044f165defa.png)

**Comment by MitchellArtz** [comment]
Just click on the X and it deletes a post

**Comment by calixo888** [comment]
@MitchellArtz So the `x` button is present, but if you try it won't delete because it's configured that way server-side. I will hide the `x` button though

**Comment by MitchellArtz** [comment]
Fixed, tested and closed
