### ISSUE TITLE
Registration - no limit on the number of causes selected

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#48]
Since there's no limit on the number of causes selected, it can result in application error and internal server error.

![Screen Shot 2020-06-17 at 6 53 02 PM](https://user-images.githubusercontent.com/64995721/84968609-c8af4200-b0cb-11ea-9950-812a3b9ae033.png)

Suggestion:
- Implement a maximum number of causes that each organization can select and display "Cause (select up to maximum #)" before the dropdown menu. Not only can this stop the overflow, but it also encourages organizations to be more concise and clear with their objectives.

**Comment by MitchellArtz** [comment]
Tested and fixed, closing
