### ISSUE TITLE
Registration - lack of website link requirements

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#50]
Allows users to add website links that don't match the required field.

eg. user can add an Instagram link under the "Linkedin link" section

![Screen Shot 2020-06-17 at 7 21 32 PM](https://user-images.githubusercontent.com/64995721/84970540-c2bb6000-b0cf-11ea-8f16-a4b4c6062911.png)

**Comment by MitchellArtz** [comment]
Not fixed, can enter Google.com under instagram

**Comment by MitchellArtz** [comment]
![image](https://user-images.githubusercontent.com/32065190/85082599-6b83c100-b19d-11ea-81d5-b5a53d75e179.png)

**Comment by calixo888** [comment]
It's not the hugest issue - it's more about the orgs doing it for their own good.
