### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#51]
When the time is between 11-12 PM on some pages it will show the next day when others will show the correct day, probably an issue of time zones in the code.

For example a post uploaded 2020-06-17 will show as 2020-06-18 if posted late at night.

**Comment by RafaelCenzano** [comment]
Possible fix, change from a date to a time delta. Show the time since its been posted. Something like posted ... (minutes ago, hours ago, days ago). Because chances are the date will be wrong somewhere in the world but the time delta won't

**Comment by calixo888** [comment]
Yeah for this we just translated the date object in Mongo to `en-US` time

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
