### ISSUE TITLE
Email icon not functional

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#65]
Whenever the email icon on the Organizations page is clicked, it brings you to the mail app, however, the email displayed is "{organization.email}" rather than the proper email of the organization.
![image](https://user-images.githubusercontent.com/32065190/85164018-b5b68200-b231-11ea-910e-09f245bcb628.png)
![image](https://user-images.githubusercontent.com/32065190/85164061-cc5cd900-b231-11ea-99f2-5b4b89f4924f.png)

**Comment by MitchellArtz** [comment]
This bug was brought up by an end-user, please fix

**Comment by jinhao27** [comment]
<a href={"mailto:" + organization.email} target="_"> should be good

**Comment by calixo888** [comment]
Fixed, thanks!
