### ISSUE TITLE
Organizations: layout of title interferes with email icon

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#74]
- At the top, we can see that long titles format correctly
- However, the title at the bottom is short enough to fit on one line, but interferes with the email icon.
<img width="352" alt="Screen Shot 2020-06-20 at 2 57 17 PM" src="https://user-images.githubusercontent.com/65053157/85209473-5aa28f00-b306-11ea-896d-1dd146e8c4f0.png">

**Comment by calixo888** [comment]
@angc7 It's a UI bug that's impossible to get around without affecting other organizations unfortunately
