### ISSUE TITLE
Organization map: geolocation service does not work

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#75]
Does not work on laptop and mobile.
<img width="1168" alt="Screen Shot 2020-06-20 at 5 07 56 PM" src="https://user-images.githubusercontent.com/65053157/85211590-99414500-b318-11ea-9f9b-610952a700ab.png">

**Comment by jinhao27** [comment]
What do you press to get this error?

**Comment by MitchellArtz** [comment]
![image](https://user-images.githubusercontent.com/32065190/85211691-98f57980-b319-11ea-9b37-21db8d6aa952.png)
Google maps and the browser geolocation API will only work over https connections. This is not an issue we can fix without SSL
