### ISSUE TITLE
SSL should be added 

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#77]
Credit to Angela Chen for discovering an issue with SSL and Google maps #75 
Some other third-party services-- should we decide to add them, won't work without SSL

**Comment by MitchellArtz** [comment]
https://devcenter.heroku.com/articles/ssl

**Comment by angc7** [comment]
Thanks! Another thing to mention is that the Google maps issue isn't reproducible for everyone; both Mitchell and I have the issue, however the Google maps geolocation function works fine for Rex and Jinhao.

**Comment by MitchellArtz** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=www.npocore.com
It seems there is SSL, it might just be misconfigured, try checking HTAccess 
@rexliu3 is reporting it shows HTTPs while it doesn't for me on any device with different networks.

**Comment by MitchellArtz** [comment]
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed
