### ISSUE TITLE
Registration causes aren't all in alphabetical order

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#88]
![image](https://user-images.githubusercontent.com/32065190/85799367-1a2f8080-b70d-11ea-8d18-7f40b3fa9056.png)

Should go like this 
`<select class="selectpicker" name="causes" data-live-search="true" multiple data-max-options="3" required>
           <option value="Advocacy and Human Rights">Advocacy and Human Rights</option>
            <option value="Animal Welfare">Animal Welfare</option>
            <option value="Arts and Culture">Arts and Culture</option>
            <option value="Children and Youth">Children and Youth</option>
            <option value="Civil Rights and Social Action">Civil Rights and Social Action</option>
            <option value="Crisis Support">Crisis Support</option>
            <option value="Disaster Relief">Disaster Relief</option>
            <option value="Emergency and Safety">Emergency and Safety</option>
            <option value="Education">Education</option>
            <option value="Environment">Environment</option>
            <option value="Female Empowerment">Female Empowerment</option>
            <option value="Health">Health</option>
            <option value="Homeless and Housing">Homeless and Housing</option>
 <option value="LGBTQ+">LGBTQ+</option>
<option value="Politics">Politics</option>
<option value="Poverty Alleviation">Poverty Alleviation</option>
            <option value="Race and Ethnicity">Race and Ethnicity</option>
            <option value="Science and Technology">Science and Technology</option>
            <option value="Social Services">Social Services</option>
            <option value="Veterans and Military Families">Veterans and Military Families</option>
          </select>`

**Comment by MitchellArtz** [comment]
https://pastebin.com/FEXLJSTF Code to make it alphabetical order

**Comment by calixo888** [comment]
Not a huge issue, it should be fine.
