### ISSUE TITLE
Organization Id doesn't replace all spaces with "-" causes browser to add "%20" to use a space

### ISSUE THREAD

**Issue by RafaelCenzano** [launchtechllc/npocore#96]
![Screen Shot 2020-07-04 at 10 53 07 AM](https://user-images.githubusercontent.com/32753063/86518215-a82dfa00-bde4-11ea-937d-56497dcb10ef.png)

**Comment by jinhao27** [comment]
i think it applies those changes to new organizations created. Need to figure out how to change existing orgs

**Comment by jinhao27** [comment]
![image](https://user-images.githubusercontent.com/53026474/86519727-b93e3180-be0b-11ea-82f2-9896dfba9e3c.png)

**Comment by RafaelCenzano** [comment]
It was like that originally, But I just changed my organization name so looks like update organization needs to have this patch as well

**Comment by jinhao27** [comment]
mm yea ill take a look

**Comment by calixo888** [comment]
Fixed by @jinhao27
