### ISSUE TITLE
Control video size limit for posts

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#98]
Macbook Air
macOS Catalina 10.15.5
Google Chrome
Post creation page

When uploading a large video to a new post, once done uploading, it redirects to an error page. There is no way out of the error page. If I press to go back, it goes back to the post creation page with the video file still attached, and I am able to resubmit the post with the same file, causing the cycle to repeat.

Something to note: the video does actually upload, but once it gets to the end and realizes that it's too large, it redirects to an error page.
There were two options:

1. Uploaded a video file that was 47.8mb large.
Result:
<img width="1440" alt="Screen Shot 2020-07-05 at 4 18 37 PM" src="https://user-images.githubusercontent.com/65053157/86541783-a98f1d80-bedd-11ea-9816-f45aca1f76fb.png">

2. Uploaded a video file that was 112mb large.
Result:
<img width="1440" alt="Screen Shot 2020-07-05 at 4 21 14 PM" src="https://user-images.githubusercontent.com/65053157/86541791-bf9cde00-bedd-11ea-907a-2a89ab0ccaef.png">

Steps to reproduce: upload a large video file. May be helpful the find the range/threshold of how much it can take (by uploading a video under 47.8mb), and then set a limit to video sizes. 

Instead of redirecting user to an error page, perhaps find a way to check the video size BEFORE uploading and then prevent the post from being submitted with that file.

**Comment by jinhao27** [comment]
set to 1000 kb
