### ISSUE TITLE
Offer profile picture resizing/cropping feature

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#99]
Not a big issue, just a suggested enhancement. This will help those who have a file with lots of blank space outside of the logo itself (hard to explain in words but easier to visualize), and the profile picture will end up misaligned.

Some examples:

HackTheFog is off-center
<img width="1104" alt="Screen Shot 2020-07-05 at 4 25 58 PM" src="https://user-images.githubusercontent.com/65053157/86541908-e9a2d000-bede-11ea-8912-bae73accc8ce.png">

STEM and Buds
<img width="1100" alt="Screen Shot 2020-07-05 at 4 46 33 PM" src="https://user-images.githubusercontent.com/65053157/86541919-1a830500-bedf-11ea-8a1b-c0ad7de47a6e.png">

**Comment by jinhao27** [comment]
already have an autocropper; works for almost all logos. I'll add a message regarding this on the register page
